### ISSUE TITLE
Styles & Scripts break in the Development

### ISSUE THREAD

**Issue by hishamco** [aspnet/live.asp.net#102]
@DamianEdwards is this by design, the expectation is the application run in all the environments without adding extra files to the project
Please let me know if I can push my PR to fix this

**Comment by DamianEdwards** [comment]
You'll need to give me more detail. Works OK for me.

**Comment by hishamco** [comment]
Perhaps you already have them but you forget to commit them in the early days, please have a look to this:
https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/Views/Shared/_Layout.cshtml#L13
https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/Views/Shared/_ValidationScripts.cshtml#L2

those just few examples for non exist resources which is needed in the Development environment

**Comment by DamianEdwards** [comment]
The project is set up such that you need to run gulp at least once for those things to be copied. The `lib` folder is not committed at all. Originally it was configured to run npm & bower restore during dotnet restore via the `"scripts"` hook in project.json, but that added a bunch of time to dev scenarios that I didn't like. It also made the deployment time to Azure longer, as it then does it during both build and publish needlessly.

I can revisit this to see if there's a middle ground that produces something I'm happy with, but it's not high on my priority list right now.

**Comment by hishamco** [comment]
My aim was to create a PR to add those files instead of run npm & bower, so the deployment will not take that time in this case furthermore it will be used in Development phase.
