### ISSUE TITLE
Tools preview version & project upgrade.

### ISSUE THREAD

**Issue by asadsahi** [aspnet/live.asp.net#103]
How come the build tool version is :  "version": "1.1.0-preview4-final", in project.json. I can only see following tools when installed .net core 1.1.

    
![image](https://cloud.githubusercontent.com/assets/3470892/20486926/6dc91dd8-aff9-11e6-9236-2bf7c8fe2036.png)

I also installed VS 2017 RC and opend my project, which added csproj file. I deleted that asuming that project.json will still work but getting this error:

AspNetCoreSpa.xproj(8,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.0-preview3-004056\Extensions
\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file ex
ists on disk.

**csproj, xproj, project.json. The whole story is really really confusing.**

**Comment by hishamco** [comment]
I think you need to close this and move it to the [Home](https://github.com/aspnet/home) repo

**Comment by DamianEdwards** [comment]
Those versions are for different things. The tools int the project.json are those that come in nuget packages ("project tools"), whereas those your showing here are the .NET Core SDK tools themselves (i.e. the `dotnet` command line).
