### ISSUE TITLE
Respond to HEAD requests for iCal

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/live.asp.net#109]
[Some iCal clients](http://www.icalhooks.com/) can make HEAD requests when determining if an iCal subscription has changed. Right now the site only listens to GET requests for ~/ical so HEAD requests for ~/ical return a 404.

**Comment by hishamco** [comment]
It returns 200 at my end!!

**Comment by GiancarloLelli** [comment]
Hey @DamianEdwards I can repro this issue, can I help?
