### ISSUE TITLE
Configure HSTS

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/live.asp.net#115]
Configure HSTS to enforce HTTPS in browsers. See https://www.troyhunt.com/understanding-http-strict-transport/

**Comment by Ky7m** [comment]
What do you think about ways of implementation:
- write your own middleware, or
- use 3rd party library (e.g. https://github.com/NWebsec/NWebsec)

NWebsec also helps with CSP (https://en.wikipedia.org/wiki/Content_Security_Policy)

**Comment by DamianEdwards** [comment]
I started it in the msbuild-migrate branch already as middleware. It's not working AFAICT when I deploy to Azure so not sure what's wrong yet.

**Comment by Ky7m** [comment]
https://github.com/aspnet/live.asp.net/commit/fe3504ee056b6657452b120d164259f6fabb4eed#diff-9d101b311b5f600a517cce4d840f680aR30

**Comment by DamianEdwards** [comment]
Fixed (finally) in 39c48c8cc830ad661fcf3f04024e057159a87755
