### ISSUE TITLE
Year in footer is wrong - © 2015 Microsoft. All rights reserved.

### ISSUE THREAD

**Issue by ghuntley** [aspnet/live.asp.net#116]
![image](https://cloud.githubusercontent.com/assets/127353/22722127/09a7e96c-ee09-11e6-9b4e-c47aec861ced.png)

**Comment by hishamco** [comment]
It's not wrong, that is the release year, please refer to this PR #33, #106

**Comment by ghuntley** [comment]
Closing this out, but 💰 this is GitHub issue is going to keep coming up. The usual format for signifying a release year is `$founded - $year`. When it's just `$founded` as witnessed by myself and those two others - it is interpreted as - "sigh, they have forgotten to update the year. Report the bug" - which is a super common problem in the software development industry. Ugh; I don't know why it is. It shouldn't be.
