### ISSUE TITLE
Dead Privacy Statement link

### ISSUE THREAD

**Issue by stibay** [aspnet/live.asp.net#123]
Seems like the link to the Privacy Statement should be https://privacy.microsoft.com/privacystatement instead of https://www.asp.net/privacy

**Comment by hishamco** [comment]
I made a PR #124 for fixing this
Thanks @stibay

**Comment by hishamco** [comment]
It got fixed in commit https://github.com/aspnet/live.asp.net/commit/51bc756f982f95d30614d8e0e58958e002b77e11
