### ISSUE TITLE
The website says it's on Air, but is it?

### ISSUE THREAD

**Issue by desjoerd** [aspnet/live.asp.net#131]
[https://live.asp.net/](https://live.asp.net/) Says it's on air right now. But the embedded video is the one of April 4th. Also there is no live stream on Scott Hanselmans youtube channel. Is it broken? or is the asp.net community standup moved to a seperate channel, because you all talked about it on the previous episode.

**Comment by hishamco** [comment]
This is not an issue, the main reason that the live.asp.net guys don't modify the option from the admin page, it happen many time in the past 😄

**Comment by alexwiese** [comment]
They should add a timeout - if it's been 24 hours since last show automatically switch to "off air"

**Comment by hishamco** [comment]
May be, but there's option in admin section to control this
