### ISSUE TITLE
Migration to ASP.NET Core 2.0.0

### ISSUE THREAD

**Issue by hishamco** [aspnet/live.asp.net#134]

**Comment by JanSichula** [comment]
Any news on this, please?

**Comment by hishamco** [comment]
@JanSichula @DamianEdwards already created a branch for ASP.NET Core 2.0.0 https://github.com/aspnet/live.asp.net/tree/2.0.0 , but I'm sure he  busy last few weeks, hopefully he will get back to this soon

**Comment by JanSichula** [comment]
@DamianEdwards Hello, would you please share some ETA for migration of code to ASP.NET Core 2.0.0? Some of us like me are waiting for v2 with an intention to fork then.

**Comment by DamianEdwards** [comment]
As soon as I find a block of 2 hours during my work day so I can live stream the migration. Sorry for the inconvenience, hopefully will happen within the next week.

**Comment by hishamco** [comment]
@DamianEdwards it's more than 6 months, since you start the migration to 2.0, I knew you 're too busy. Me or someone one the community can continue on this ..

One more thing hopefully someone can maintain the repository .. I seen many issues & PRs for long time without any action

**Comment by DamianEdwards** [comment]
I have a branch I've been working in recently. I appreciate the offer but this is a site I'll continue to maintain for the time being and I don't intend to make any changes other than eventual version updates.

**Comment by hishamco** [comment]
All the best ...
