### ISSUE TITLE
Remove YouTube black borders

### ISSUE THREAD

**Issue by hishamco** [aspnet/live.asp.net#138]
The black borders in the YouTube thumbnails is ugly little, I did some experiment to make the thumbnails like this:
![capture](https://user-images.githubusercontent.com/3237266/28137272-5a9f4c8c-6755-11e7-83da-3ff6f2a78035.PNG)
 
If the change looks fine with you, I will make a PR for this

**Comment by aafvstam** [comment]
The YouTube API only returns the thumbnails with black overflow areas. There is no option to get them returned in white background. Only option would be to crop the returned image to the actual thumbnail size without the borders.

**Comment by hishamco** [comment]
Nope, medium quality images come without black borders, IMHO this issue can be solved either by cropping as you mentioned before or using some CSS to rid off the black border

**Comment by aafvstam** [comment]
Quote: "The image is not cropped, but may include black bars so that the size is correct." 
[https://developers.google.com/youtube/v3/docs/thumbnails](url)

**Comment by aafvstam** [comment]
Just tested, the mediom indeed gives no black borders despite what the documentation mentioned. Gave me some other layout issues though resulting in one black border on the right :-)
