### ISSUE TITLE
Support show notes in MD files

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/live.asp.net#141]
With a physical file storage and Azure Blob storage implementations. Just rely on file name conventions for associating show note files with the matching episode. We should show a link on the home page next to episodes for those with show notes, that when clicked renders the show notes on the live.asp.net website, e.g. https://live.asp.net/episodes/show-title-slug-here

**Comment by hishamco** [comment]
LGTM

Such a feature is requested a lot in the past, nothing but why we didn't make the link go to the original blog post, that are written usually by @csharpfritz or @LadyNaggaga instead of creating the notes again

**Comment by DamianEdwards** [comment]
Because we intend to change the flow, such that we don't post them there anymore, but rather keep them on the live.asp.net site.

**Comment by hishamco** [comment]
Looks good 👍
