### ISSUE TITLE
Replicated Date Title

### ISSUE THREAD

**Issue by IvandroFabiaeFilhos** [aspnet/live.asp.net#144]
The event date appear replicated to all episodes!

**Comment by hishamco** [comment]
You 're right, but It's working on staging environment!! @DamianEdwards is it caching issue or it's related to the YouTube copier that you are working on?!! but the dates in the YotTube playlist is still correct

**Comment by DamianEdwards** [comment]
I'm fixing it now. The code is incorrectly using the date the item was added to the playlist, not the video recording date.

**Comment by hishamco** [comment]
Strange!! but it was working since the live.asp.net was created, last commit by you Jun 27 and I'm checking the website from time to time it was working fine, I didn't realize there's incorrect code!!

**Comment by DamianEdwards** [comment]
I changed the settings of the production site to read from the new playlist which unearthed the bug.

**Comment by DamianEdwards** [comment]
Fixed now.

**Comment by hishamco** [comment]
Great, but why the `New` label doesn't show up in the last episode?
```csharp
public bool IsNew => !IsInFuture && (DateTimeOffset.Now - ShowDate).TotalDays <= 7;
```
I presume the condition is correct
