### ISSUE TITLE
Home page currently showing "On Air"

### ISSUE THREAD

**Issue by lukecolbourn** [aspnet/live.asp.net#147]
Home page currently showing "On Air", but you're not on air. Sad times.

**Comment by lukecolbourn** [comment]
I guess there is not an admin message and there is a live show embedded or the live show HTML is set.
Close.

`public bool IsOnAir => !HasAdminMessage && (IsLiveShowEmbedded || !string.IsNullOrEmpty(LiveShowHtml));`

**Comment by hishamco** [comment]
This is not an issue, seems one the team forget to set the next day
