### ISSUE TITLE
Skip deleted videos in the playlist

### ISSUE THREAD

**Issue by terrimorton** [aspnet/live.asp.net#155]
Currently, when a video in the YouTube playlist ([https://www.youtube.com/watch?v=WmDXgO0f-MQ&list=PL1rZQsJPBU2StolNg0aqvQswETPcYnNKL](https://www.youtube.com/watch?v=WmDXgO0f-MQ&list=PL1rZQsJPBU2StolNg0aqvQswETPcYnNKL)) is deleted, the web app will fail with a 500 error and a null reference exception.

We need to skip deleted videos in the playlist.

**Comment by hishamco** [comment]
So that's why the 505 show up in the [live.asp.net](live.asp.net), nice catch
