### ISSUE TITLE
Add to Google Calendar

### ISSUE THREAD

**Issue by TimMurphy** [aspnet/live.asp.net#26]
Current link to next standup (webcals://live.asp.net/ical) does not work with Google Calendar.

**Comment by TimMurphy** [comment]
@DamianEdwards if you approve this issue I'd like to work on a pull request for it.

**Comment by Eilon** [comment]
That would be great.

**Comment by DamianEdwards** [comment]
@TimMurphy I've updated the UI to be a dropdown now, so when you do this, please just add a new menu item. Cheers!

**Comment by TimMurphy** [comment]
Will do. Likely to have crack tomorrow.
