### ISSUE TITLE
Unable to restore packages

### ISSUE THREAD

**Issue by hishamco** [aspnet/live.asp.net#28]
I'm facing an issue when I run **dnu restore** it show unable to locate [dependency]

**Comment by Eilon** [comment]
Screenshot?

**Comment by hishamco** [comment]
![bug](https://cloud.githubusercontent.com/assets/3237266/9128901/7769797c-3cd8-11e5-8932-b401b16dbaea.PNG)

**Comment by DamianEdwards** [comment]
Can you show the part where it reports what `nuget.config` and feeds were used?

**Comment by hishamco** [comment]
NuGet Config files used:
    C:\Users\Hisham\AppData\Roaming\NuGet\NuGet.Config
    C:\Users\Hisham\Source\Repos\live.asp.net\NuGet.Config

**Comment by hishamco** [comment]
Seems we need to change the NuGet.config to read the online feed, shall I made a PR for that?

**Comment by DamianEdwards** [comment]
Not sure what you mean. It's working fine for me and during deployment to azure, so it should work everywhere.

**Comment by hishamco** [comment]
It works now after i add the following feeds:

``` xml
<add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2" />
<add key="NuGet" value="https://nuget.org/api/v2/" />
```

if you notice in **NuGet.config** there's a <clear/> which causes the issue, I think we need to change the NuGet.config, so let me know if can submit a PR now

**Comment by hishamco** [comment]
Perhaps all the packages needed is already there in your end?!!

**Comment by DamianEdwards** [comment]
This project shouldn't be using any packages from the AspNetVNext feed, and everything on the nuget v2 feed should also be on the nuget v3 feed (which is the one this project is using). So we need to figure out the root cause rather than add more feeds.

**Comment by DamianEdwards** [comment]
Can you try running a restore with --no-cache, e.g. `dnu restore --no-cache`? With the original nuget.config in the repo.

**Comment by hishamco** [comment]
I already restore them after adding AspNetVNext feed, is there a way to revert that using command line?

**Comment by Eilon** [comment]
If you use the `--no-cache` flag it will ignore any previously installed package. Do a `git clean -xdf` first, though.

**Comment by hishamco** [comment]
They restore them without `--no-cache`?!! shall i remove the packages folder entries?

**Comment by Eilon** [comment]
Please revert any local changes to the repo, run `git clean -xdf` and then run `dnu restore --no-cache`, and then build.

**Comment by hishamco** [comment]
I already ran `git clean -xdf` and `dnu restore --no-cache`, seems restore them quickly from my local packages, strange!!
Let me clean the packages & dnu cache folders and try again

**Comment by hishamco** [comment]
I already did, I got the error that I post in my first thread, but whenever I add the feeds that I mentioned before everything works as excepted.
FYI I upgrade the dnvm to **1.0.0-beta7-12302**

**Comment by Eilon** [comment]
Can you run `dnu feeds list` and show the output? I have a feeling that some feeds are disabled...

**Comment by hishamco** [comment]
There's a feed named `api.nuget.org/v3` which is disabled as you said, believe it or not this is the first time i see this command, please let me know how can I enable it

**Comment by Eilon** [comment]
Please run the command and show us the output.

**Comment by hishamco** [comment]
As I told you before, here is a screenshot
![capture](https://cloud.githubusercontent.com/assets/3237266/9141307/5c69f954-3d40-11e5-870a-92d47492c738.PNG)

**Comment by Eilon** [comment]
Can you run it from within the project folder? The NuGet feeds depend on the exact location of the project.

**Comment by hishamco** [comment]
![capture](https://cloud.githubusercontent.com/assets/3237266/9142121/5942f95a-3d46-11e5-9f53-8fe069df128b.PNG)

**Comment by DamianEdwards** [comment]
Is there any chance the v3 feed is blocked from your location? Can you browse to that URL?

**Comment by hishamco** [comment]
Whenever I write that url, json file popups into the browser

**Comment by DamianEdwards** [comment]
Can you ensure you have the latest VS tooling installed (the beta6 update) as well SSD the latest NuGet VS client. If so, open the feeds config dialog from Tools -> NuGet Package Manager -> Settings and then hit OK.

**Comment by hishamco** [comment]
I already installed the latest DVNM version, I will check the NuGet version and i will follow your instructions

**Comment by hishamco** [comment]
Well done :)
thanks @DamianEdwards

**Comment by JimiC** [comment]
The VS tooling for beta 6 is not updating the `dnvm`.ps1 file and it remains at beta5. I have already left a comment at the VS tooling site about it. You need to manually update the `dnvm`.ps1 file from the dev branch or execute dnvm update-self (this will update `DNVM` to beta7 when this is written).

**Comment by hishamco** [comment]
I already update it myself, but I follow the @DamianEdwards instructions it works fine, thanks @JimiC
