### ISSUE TITLE
Remove unused client side dependencies

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/live.asp.net#36]
The client-side dependencies from initial project bootstrap can be removed:
https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/bower.json#L6-L7

```
"bootstrap-touch-carousel": "0.8.0",
 "hammer.js": "2.0.4"
```

They are not used. The website CSS stylesheet will require removal of `bootstrap-touch-carousel` related code as well.

If removed, it will simplify and clarify client-side dependencies in project.

Is it OK to PR this?

Thanks!

**Comment by DamianEdwards** [comment]
Sure
