### ISSUE TITLE
@Html.ApplicationInsightsJavaScript creates deprecated script language attribute

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/live.asp.net#40]
I just can't find where to submit this one, so I post it here as web site is using it:
https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/Views/Shared/_AnalyticsHead.cshtml#L18

``` razor
 @Html.ApplicationInsightsJavaScript(...)
```

creates `<script language="javascript"></script>` tag which is non-HTML5 attribute (obsolete one). 
In HTML5 all script tag without type are just `JavaScript` types - the `language` should not be used at all.
I could move it to related project (but I cannot figure one which one it should be).
https://developer.mozilla.org/en/docs/Web/HTML/Element/script#Attributes
Thanks!

**Comment by DamianEdwards** [comment]
Thanks, I'd already logged that over on their repo at Microsoft/ApplicationInsights-aspnet5#101

**Comment by peterblazejewicz** [comment]
Thanks!
