### ISSUE TITLE
Refresh the page when it's ShowTime

### ISSUE THREAD

**Issue by M-Zuber** [aspnet/live.asp.net#43]
If I understood what was said during the 8/11 standup, the solution for this would be to start a simple polling as the showtime gets closer?
Assuming that yes, I would like to take a stab at that

**Comment by hishamco** [comment]
Last week I notice a latency the time stopped while the YouTube player not started yet

**Comment by peterblazejewicz** [comment]
@M-Zuber 
AFAIK the page needs to either reload - so HangOut embed partial gets incorporated into page and show starts streaming or JS code should modify view to embed HangOut stream:
https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/Views/Home/Index.cshtml#L34-L38
If I'm not wrong, the current `endCallback` closure just clears counter:
https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/wwwroot/js/site.js#L131-L133

**Comment by M-Zuber** [comment]
@peterblazejewicz you are correct, in today's standup it was verified that the page needs to be refreshed.
#45 seems to take care of it quite nicely
