### ISSUE TITLE
Css file is not minified on Staging and Production environments

### ISSUE THREAD

**Issue by Ky7m** [aspnet/live.asp.net#44]
I guess that it's just mechanical error, 
because in _Layout.cshtml file 
https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/Views/Shared/_Layout.cshtml#L21
we have 
`<link rel="stylesheet" href="~/css/site.css" asp-file-version="true" />"`
instead
`"<link rel="stylesheet" href="~/css/site.min.css" asp-file-version="true" />"`
resulting, on production we get not minified file.

**Comment by hishamco** [comment]
You are right, but the file is not big, it will be nice if we use bundling after minification which almost done

**Comment by peterblazejewicz** [comment]
The default Gulp tasks are there:
https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/gulpfile.js#L29
https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/gulpfile.js#L45

**Comment by hishamco** [comment]
Thanks @peterblazejewicz
