### ISSUE TITLE
Latest Episode Issue

### ISSUE THREAD

**Issue by hishamco** [aspnet/live.asp.net#46]
I notice this week that the latest not shows yet, after the standup finished, it takes more than couple of hours. I'm not sure if there an issue for the latency

**Comment by froman118** [comment]
Scott has to add the video to the Community Standup playlist in YouTube for it to show up. He was hitting the road right after the show ended so likely didn't have a chance to add it.

Ha, he added it just as I was typing that.

**Comment by hishamco** [comment]
Thanks @froman118
