### ISSUE TITLE
Bootstrap.css is not exist in Development

### ISSUE THREAD

**Issue by hishamco** [aspnet/live.asp.net#47]
The `bootstrap.css` path is not exist in both Development https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/Views/Shared/_Layout.cshtml#L12 and Staging & Production fallback https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/Views/Shared/_Layout.cshtml#L17

**Comment by DamianEdwards** [comment]
It gets added when the bower components are restored. VS does this automatically but without VS you have to run a `bower install` from the cmd line.

**Comment by hishamco** [comment]
Thanks

**Comment by JimiC** [comment]
@DamianEdwards According to [this article](http://addyosmani.com/blog/checking-in-front-end-dependencies/) you may wonna consider adding the `bower_components` folder to the repo.
