### ISSUE TITLE
Coding conventions

### ISSUE THREAD

**Issue by matsprea** [aspnet/live.asp.net#54]
Since I'm learning _the hard way_ (in a couple of PR) how to properly style the code for this repo, I was wandering if there is a _coding conventions_ doc that we can read before submitting a PR to improve the process.

Maybe this one [C# Coding Conventions](https://msdn.microsoft.com/en-us/library/Ff926074%28v=vs.120%29.aspx) ?

IMHO it will be useful to link the _coding conventions_ doc in the [guidelines for contributing](https://github.com/aspnet/live.asp.net/blob/dev/CONTRIBUTING.md).

**Comment by hishamco** [comment]
This may a great guideline https://github.com/aspnet/Home/wiki/Engineering-guidelines#extension-method-patterns because `aspnet` repos already use it :smile:

**Comment by matsprea** [comment]
Thanks, my fault, sorry.

**Comment by Eilon** [comment]
BTW the default guidance in general for any repo is "follow the conventions already used in the repo/file/project. The official guidelines we use deliberately avoid going into many details because it's generally not worth it.
