### ISSUE TITLE
Add AppVeyor, Travis build status

### ISSUE THREAD

**Issue by hishamco** [aspnet/live.asp.net#55]

**Comment by JimiC** [comment]
Definitely add Travis. AppVeyor needs to improve their queuing time (it can take up to 30 min till the changes get build).

**Comment by hishamco** [comment]
I already made such PR in many of `aspnet` repos with help of @Eilon which he adds the token of it

**Comment by DamianEdwards** [comment]
We don't build this repo at all automatically right now as it's not part of the ASP.NET source. Having a CI build would be nice but I already push to staging on Azure automatically so it builds as part of that and I can see if it fails.

**Comment by hishamco** [comment]
Thanks @DamianEdwards
