### ISSUE TITLE
Run in OSX

### ISSUE THREAD

**Issue by rmarinho** [aspnet/live.asp.net#56]
It would be nice if we could just clone and run it locally from OSX with kestrel.

**Comment by hishamco** [comment]
:+1: I will make a PR soon to support `Kestrel` too

**Comment by DamianEdwards** [comment]
This will require making the app target .NET Core (dnxcore50). This will potentially impact the dependencies it has as they also need to run on .NET Core, e.g. the Windows Azure Storage client, the YouTube API client. I can take a look to see if we can make it work but I have no need for it to run cross-platform right now so I purposely removed .NET Core as a target.

**Comment by DamianEdwards** [comment]
The YouTube API hasn't yet been updated for .NET Core so I'm closing this for now. We can revisit this in the future once that and the WindowsAzure.Storage client are ready for .NET Core and cross-platform.
