### ISSUE TITLE
MS Logo 404

### ISSUE THREAD

**Issue by YumiFuze** [aspnet/live.asp.net#57]
![image](https://cloud.githubusercontent.com/assets/12098548/9353591/d7a70484-46ac-11e5-88ea-a563d3856035.png)

**Comment by hishamco** [comment]
@YumiFuze can you check it in staging https://asp-standup-staging.azurewebsites.net/ the logo got `200 OK` but seems the image could not loaded

![capture](https://cloud.githubusercontent.com/assets/3237266/9355824/1e18c4a2-4685-11e5-8a3b-65a278585ae6.PNG)

**Comment by matsprea** [comment]
I have the same issue, both in production and staging, but it works fine on my machine on localhost.

**General**

```
Remote Address:191.238.8.26:443
Request URL:https://live.asp.net/images/Microsoft_logo.svg
Request Method:GET
Status Code:404 Not Found
```

**Response Headers**

```
HTTP/1.1 404 Not Found
Content-Length: 103
Content-Type: text/html
Server: Microsoft-IIS/8.0
X-Powered-By: ASP.NET
Date: Wed, 19 Aug 2015 18:22:11 GMT
```

**Response Body**

```
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```

**Comment by hishamco** [comment]
Sorry I think it was cached, now i got `404`

**Comment by hishamco** [comment]
@DamianEdwards can you please check if there's an issue

**Comment by DamianEdwards** [comment]
It's being investigated, appears to be an Azure issue on the server.

**Comment by YumiFuze** [comment]
Hi all, It appears to be resolved now. :)

Kind Regards,

​yumiFUZE ​
Support Team

**Comment by hishamco** [comment]
:+1:
