### ISSUE TITLE
Feature: display a short announcement banner on the site

### ISSUE THREAD

**Issue by akoeplinger** [aspnet/live.asp.net#66]
This would allow you to post a quick update in case you had to reschedule/cancel the meeting and avoids confusion like https://twitter.com/khellang/status/654211759000145920.

e.g. **"We had to cancel the meeting for 2015-10-13 and will be back next week. Sorry"**

**Comment by hishamco** [comment]
The time is already updated in the header of live.asp.net

**Comment by akoeplinger** [comment]
@hishamco yes, but that doesn't provide context on _why_ it was updated when e.g. an hour ago it showed "2 hrs 10mins until standup" and I'm left wondering what happened.

**Comment by froman118** [comment]
Just ran into this yesterday. I had a calendar event setup (via downloaded ICS) for yesterday, 10/28/15, at 3:30 PM. Pop onto the site to see what's going on and nothing except the countdown for next week's show.
