### ISSUE TITLE
Logo svg not served

### ISSUE THREAD

**Issue by benaadams** [aspnet/live.asp.net#69]
The logo svg is not being served and returning a 404 url https://live.asp.net/images/Microsoft_logo.svg

This means ut shows up as a broken image in chrome

![missing logo](http://aoa.blob.core.windows.net/aspnet/logo.png)

Also in Edge

![missing-logo](http://aoa.blob.core.windows.net/aspnet/logo-edge.png)

**Comment by Muchiachio** [comment]
This is actually a gif of "things happening on @DamianEdwards monitors". :smile:

**Comment by hishamco** [comment]
It was there before, let me look have a look @benaadams 
nice catch .. thanks

**Comment by benaadams** [comment]
@hishamco File seems to be there, might be a mime type/file extension thing?

**Comment by hishamco** [comment]
The png file is there not the svg :(

**Comment by hishamco** [comment]
It's related to the issue #57
/cc @DamianEdwards

**Comment by benaadams** [comment]
Ah, is in repository https://github.com/aspnet/live.asp.net/tree/dev/src/live.asp.net/wwwroot/images

**Comment by hishamco** [comment]
Yep it's there, but the user got **404**, as I said before it's related to issue #57

**Comment by hishamco** [comment]
@benaadams it got fixed, @DamianEdwards can we know why the issue happen frequently?

**Comment by DamianEdwards** [comment]
It was an issue with Azure Web Apps configuration they fixed in the latest update.

**Comment by hishamco** [comment]
You already mention that in issue #57, but I surprised why it happen again
Thanks @DamianEdwards
