### ISSUE TITLE
Make ics file have a suffix

### ISSUE THREAD

**Issue by flcdrg** [aspnet/live.asp.net#72]
If I download the ics file on a Windows Phone, it either saves the file as 'ics[1]' in downloads, or offers to open the file by looking for an app (which then fails).

I think if the file downloaded was named with '.ics' as a file suffix (eg. 'liveaspnet.ics' or 'meeting.ics'), then this would reduce the problem.

**Comment by hishamco** [comment]
@flcdrg I can reproduce this issue in my Window Phone, but could you please it works on Android & iOS or this the case for WP?

**Comment by flcdrg** [comment]
I only have a Windows Phone

**Comment by hishamco** [comment]
I see, I will try to test it in the Android too

**Comment by hishamco** [comment]
FYI in Android the downloaded file is `ical.ics`

**Comment by JimiC** [comment]
It's an issue only seen in IE 10-. Had the same situation with another project of mine.

**Comment by hishamco** [comment]
Strange!!
