### ISSUE TITLE
[Bug] ON AIR label still show up after ~ 12 hour later

### ISSUE THREAD

**Issue by hishamco** [aspnet/live.asp.net#76]

**Comment by hishamco** [comment]
I notice this bug again this week, I'm sure this bug is caused by this [line](https://github.com/aspnet/live.asp.net/blob/0af774b6aafae6b760dc98852b4f6be7a98c40be/src/live.asp.net/ViewModels/HomeViewModel.cs#L17)

**Comment by JimiC** [comment]
Looks like @DamianEdwards is _reeeeeeally_ busy.

**Comment by hishamco** [comment]
Sure 😄

**Comment by kdaveid** [comment]
I think Damian just hasn't updated the next "LiveShowDetails" on Azure... If he would do that, not committing any LiveShowEmbedUrl or AdminMessage THEN it would fall back to [NextShowScheduled](https://github.com/aspnet/live.asp.net/blob/0af774b6aafae6b760dc98852b4f6be7a98c40be/src/live.asp.net/Views/Home/Index.cshtml#L41)... 

@DamianEdwards : When can we join you next time? ;-)

**Comment by DamianEdwards** [comment]
Yeah we just hadn't cleared the broadcast URL from the admin screen. The bug is us.

**Comment by JimiC** [comment]
@DamianEdwards And we are those who are `bug`ging you. :laughing:
