### ISSUE TITLE
Youtube  & China

### ISSUE THREAD

**Issue by John0King** [aspnet/live.asp.net#79]
Youtube is not available in  China  :(

**Comment by DamianEdwards** [comment]
We've long talked about getting these videos on to channel9. @shanselman we should really make that a priority to help the folks in China.

**Comment by shanselman** [comment]
Gotcha. I will work with @csharpfritz and figure out that script we need to copy to Channel 9.

**Comment by aminebizid** [comment]
How can they live without YouTube. Ok I stop politics now 😏
