### ISSUE TITLE
ASP.NET 5 RC1 Update 1 Corruption

### ISSUE THREAD

**Issue by ghost** [aspnet/live.asp.net#80]
Installing "ASP.NET 5 RC1 Update 1" on a clean installation of Visual Studio 2015 (any version) with Update 1, will forever corrupt your Visual Studio 2015 installation, making it impossible to edit .cshtml files.  The following issues have been opened:

[Can't open .cshtml files with the Visual Studio 2015 HTML Editor (ASP.NET 5 RC1 Update 1)](https://connect.microsoft.com/VisualStudio/feedback/details/2323617/cant-open-cshtml-files-with-the-visual-studio-2015-html-editor-asp-net-5-rc1-update-1)
[Can't open .cshtml files with the Visual Studio 2015 HTML Editor (post ASP.NET 5 RC1 Update 1) #390](https://github.com/aspnet/Tooling/issues/390)

There is no fix for this!  Uninstalling everything related to Visual Studio (all versions) and .NET (all versions), or doing a clean install of Windows, and then reinstalling everything (a week long process) is not an option.  When is there going to be a HOTFIX for this, so they we can again use these workstations?  It has been over 2 months since you have been notified of this, and NOTHING has been done!

Here are just 2 of the MANY RTM or Microsoft Recommended Updates that Visual Studio will ask to install that contain this corrupt BETA code:

[Microsoft ASP.NET and Web Tools](https://visualstudiogallery.msdn.microsoft.com/c94a02e9-f2e9-4bad-a952-a63a967e3935?SRC=VSIDE)
Microsoft Azure SDK 2.8.2 (Web Platform Installer)

Additionally, I have noticed that if this is installed on a Windows 10 machine, it will cause Windows 10 itself to become corrupted and require an in-place upgrade of Windows 10 to correct everything that it breaks.

How could ANY team at Microsoft be allowed to release BETA software into the RTM life cycle of other products?

**Comment by hishamco** [comment]
I don't think this is the right repo

**Comment by Eilon** [comment]
@Kaelum I'm sorry you're running into all these issues - this of course is not the expected experience. I bumped the discussion on https://github.com/aspnet/Tooling/issues/390 to make sure the VS tooling folks see this again. (This repo is specifically for discussing the live.asp.net web site, so it's unlikely the right VS tooling people would be monitoring this discussion here.)
