### ISSUE TITLE
Issue in last episode date

### ISSUE THREAD

**Issue by hishamco** [aspnet/live.asp.net#85]
The last episode date is Jun 21, 2016 not 25
/cc @jongalloway @DamianEdwards @shanselman

**Comment by JimiC** [comment]
That's the day @shanselman published it on youtube (after all he mentions in the title the correct day). @DamianEdwards [recording](https://www.youtube.com/watch?v=_nF3BQmrdkU) is of 21st June. It's a trivial issue and I don't think we should make a big deal out of it.

**Comment by hishamco** [comment]
I miss this week stand up, but when I notice that, I report it as an issue, I know it's not a big deal, but it's issue if i'm not wrong 😄

**Comment by shanselman** [comment]
Thanks Folks!
