### ISSUE TITLE
RTM 

### ISSUE THREAD

**Issue by aminebizid** [aspnet/live.asp.net#86]
Damian are you planning to migrate this solution to 1.0.0?

**Comment by DamianEdwards** [comment]
Of course! Will do so as soon as Azure App Service web sites deploys .NET Core 1.0 RTM bits.

**Comment by gdoron** [comment]
@DamianEdwards Any ETA on that?

**Comment by DamianEdwards** [comment]
Did it today live on the standup! :smile:

**Comment by aminebizid** [comment]
Thanks

**Comment by aminebizid** [comment]
Do I need uninstall RC1 & RC2 before installing RTM?

**Comment by DamianEdwards** [comment]
No

**Comment by aminebizid** [comment]
Great and wonderful response

**Comment by DamianEdwards** [comment]
I like to be efficient 😃

**Comment by aminebizid** [comment]
Damian, sorry I know this is not the correct place to post this 
Our experts adviced us to not migrate to Core because a guy from Microsoft France told them that there will be big breaking changes  coming in next version.
As I'm following community standup I know that these changes will only impact tooling.
Could you please confirm.
Cheers

**Comment by gdoron** [comment]
I believe this guy had no clue and was only guessing.
And regardless, even though rc1 to RTM  had quite a few breaking changes, migrating isn't that hard.

Obviously changes between releases would be even easier.

**Comment by aminebizid** [comment]
Thanks gdoron but I need a response from Damian because I will forward it.

**Comment by hishamco** [comment]
@zigzag95 you can check the breaking changes for the latest bits in [announcements repo](https://github.com/asp net/announcements)
