### ISSUE TITLE
Add to calendar dropdown broken?

### ISSUE THREAD

**Issue by greenygh0st** [aspnet/live.asp.net#89]
When I click the "add to calendar" dropdown nothing happens in Edge, Firefox or Chrome. I need to fiddle a little more to see whats actually going wrong.

**Comment by DamianEdwards** [comment]
This is my fault. I removed jQuery from the home page, forgetting it was used for the dropdown. I'll fix.

**Comment by DamianEdwards** [comment]
52cfda6c5421aa186c515387d67d11fd4d04b8e6

**Comment by greenygh0st** [comment]
Thanks for the quick fix!
