### ISSUE TITLE
ics file not working

### ISSUE THREAD

**Issue by philipp985** [aspnet/live.asp.net#94]
When I dowload the ics file it seems to be an empty file. Opening it with outlook is not possible and even opening it with notepad displays just an empty page.

**Comment by hishamco** [comment]
@philipp985 the ics file works fine on the [staging environment](https://ms-asp-standup-staging.azurewebsites.net/), @DamianEdwards did you push the latest changes to the production environment, or is there something else causes this issue?

**Comment by philipp985** [comment]
Ah ok, thanks for the information I can confirm that.

**Comment by hishamco** [comment]
@DamianEdwards I notice the latest episode is not show up in the production, but its shown in the staging. Can you please push the changes

**Comment by hishamco** [comment]
@philipp985 is this got fixed, you can check it now

**Comment by hishamco** [comment]
@philipp985 could you please close this, it's fixed
