### ISSUE TITLE
Looking for better Performance

### ISSUE THREAD

**Issue by hishamco** [aspnet/live.asp.net#96]
While announcing ASP.NET Core 1.1 Preview 1, it would be nice to improve the performance using some of the new features such as Response Caching & Response Compression, this may a continuation of what @spboyer did in PR #93 

/cc @DamianEdwards

**Comment by DamianEdwards** [comment]
Yeah I'm in the process up updating this site to 1.1.0-preview1, I'll see if either of these middleware improve the home page response time/size.

**Comment by hishamco** [comment]
I was planning to push a PR, but if you're in the process of updating to 1.1.0-preview1, please have a look if these middlewares may improve the home page response time/size

**Comment by hishamco** [comment]
BTW there 're a lot of PRs with no action taken from long long time, hopefully if someone have a look to them
